theme = "catppuccin_mocha"
# theme = "onedarker"
# theme = "zed_onedark"
# theme = "dracula"

[keys.normal]
A-y = [":clipboard-yank"]
A-m = ["extend_to_line_bounds", "yank", "paste_after"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[editor]
mouse = true
rulers = [80]
# Minimum severity to show a diagnostic after the end of a line:
end-of-line-diagnostics = "warning"

[editor.inline-diagnostics]
prefix-len = 10
cursor-line = "error"
other-lines = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
