theme = "hex_steel"

[keys.normal]
A-y = [":clipboard-yank"]
A-m = ["extend_to_line_bounds", "yank", "paste_after"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

[editor]
mouse = true
bufferline = "always"
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
