[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "codebook"]
auto-format = true
