[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "codebook"]
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo", "codebook"]
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "bash"
language-servers = ["bash-language-server", "codebook"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["ruff", "jedi", "pylsp", "codebook"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "codebook"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "superhtml", "codebook"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
language-servers = ["jsonnet-language-server", "codebook"]
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "codebook"]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "codebook",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "codebook",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[language-server.typescript-language-server.config.preferences]
importModuleSpecifierPreference = "relative"

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "codebook",
]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
language-servers = ["helm_ls", "codebook"]
auto-format = true
