[language-server.cspell]
command = "cspell-lsp"
args = [
  "--stdio",
  "--dictionary",
  "/Users/robert/.config/helix/cspell-dictionary",
]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "cspell"]
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "cspell"]
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo", "cspell"]
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "bash"
language-servers = ["bash-language-server", "cspell"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["ruff", "jedi", "pylsp", "cspell"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "cspell"]
formatter = { command = "prettier", args = ["--parser", "markdown"] }

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "superhtml", "cspell"]
formatter = { command = "prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
language-servers = ["jsonnet-language-server", "cspell"]
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "cspell"]
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "cspell",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "cspell",
]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[language-server.typescript-language-server.config.preferences]
importModuleSpecifierPreference = "relative"

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
  "cspell",
]
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }

# [[language]]
# name = "yaml"
# language-servers = [
#   "yaml-language-server",
#   "docker-compose-langserver",
#   "cspell",
# ]
# auto-format = true

[[language]]
name = "yaml"
file-types = ["yaml", "yml"]
auto-format = true
